/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthResponse { 'token' : string, 'user' : UserPublic }
export interface DecisionRequest {
  'mood' : [] | [string],
  'cuisinePreference' : [] | [string],
  'budgetOverride' : [] | [bigint],
}
export interface DecisionResult {
  'sessionId' : string,
  'picks' : Array<FoodItem>,
}
export interface FoodItem {
  'id' : string,
  'name' : string,
  'tags' : Array<string>,
  'swipeCount' : bigint,
  'cuisineType' : string,
  'deliveryTime' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
  'rating' : number,
  'price' : bigint,
  'whyThis' : string,
  'restaurant' : string,
  'reason' : string,
}
export interface HistoryEntry {
  'id' : string,
  'userId' : string,
  'feedback' : string,
  'savedAt' : bigint,
  'foodItem' : FoodItem,
}
export interface ShareRecord {
  'createdAt' : bigint,
  'createdBy' : string,
  'shareId' : string,
  'foodItem' : FoodItem,
}
export interface SwipeRecord {
  'direction' : string,
  'userId' : string,
  'swipedAt' : bigint,
  'foodId' : string,
}
export interface UserPreferences {
  'notificationsEnabled' : boolean,
  'dietaryType' : string,
  'cuisines' : Array<string>,
  'budget' : [] | [bigint],
}
export interface UserPublic {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'preferences' : UserPreferences,
}
export interface _SERVICE {
  'addHistory' : ActorMethod<
    [string, string, string],
    { 'ok' : HistoryEntry } |
      { 'err' : string }
  >,
  'createShareLink' : ActorMethod<
    [string, string],
    { 'ok' : ShareRecord } |
      { 'err' : string }
  >,
  'getHistory' : ActorMethod<
    [string],
    { 'ok' : Array<HistoryEntry> } |
      { 'err' : string }
  >,
  'getProfile' : ActorMethod<
    [string],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'getSharedPick' : ActorMethod<
    [string],
    { 'ok' : ShareRecord } |
      { 'err' : string }
  >,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : AuthResponse } |
      { 'err' : string }
  >,
  'recordSwipe' : ActorMethod<
    [string, string, string],
    { 'ok' : SwipeRecord } |
      { 'err' : string }
  >,
  'refineDecision' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : DecisionResult } |
      { 'err' : string }
  >,
  'runDecision' : ActorMethod<
    [string, DecisionRequest],
    { 'ok' : DecisionResult } |
      { 'err' : string }
  >,
  'savePick' : ActorMethod<
    [string, string],
    { 'ok' : HistoryEntry } |
      { 'err' : string }
  >,
  'signup' : ActorMethod<
    [string, string, string],
    { 'ok' : AuthResponse } |
      { 'err' : string }
  >,
  'undoLastSwipe' : ActorMethod<
    [string],
    { 'ok' : SwipeRecord } |
      { 'err' : string }
  >,
  'updatePreferences' : ActorMethod<
    [string, UserPreferences],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];