/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'swipeCount' : IDL.Nat,
  'cuisineType' : IDL.Text,
  'deliveryTime' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'whyThis' : IDL.Text,
  'restaurant' : IDL.Text,
  'reason' : IDL.Text,
});
export const HistoryEntry = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'feedback' : IDL.Text,
  'savedAt' : IDL.Int,
  'foodItem' : FoodItem,
});
export const ShareRecord = IDL.Record({
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'shareId' : IDL.Text,
  'foodItem' : FoodItem,
});
export const UserPreferences = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'dietaryType' : IDL.Text,
  'cuisines' : IDL.Vec(IDL.Text),
  'budget' : IDL.Opt(IDL.Nat),
});
export const UserPublic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'preferences' : UserPreferences,
});
export const AuthResponse = IDL.Record({
  'token' : IDL.Text,
  'user' : UserPublic,
});
export const SwipeRecord = IDL.Record({
  'direction' : IDL.Text,
  'userId' : IDL.Text,
  'swipedAt' : IDL.Int,
  'foodId' : IDL.Text,
});
export const DecisionResult = IDL.Record({
  'sessionId' : IDL.Text,
  'picks' : IDL.Vec(FoodItem),
});
export const DecisionRequest = IDL.Record({
  'mood' : IDL.Opt(IDL.Text),
  'cuisinePreference' : IDL.Opt(IDL.Text),
  'budgetOverride' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'addHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : HistoryEntry, 'err' : IDL.Text })],
      [],
    ),
  'createShareLink' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ShareRecord, 'err' : IDL.Text })],
      [],
    ),
  'getHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(HistoryEntry), 'err' : IDL.Text })],
      [],
    ),
  'getProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'getSharedPick' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ShareRecord, 'err' : IDL.Text })],
      ['query'],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
      [],
    ),
  'recordSwipe' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SwipeRecord, 'err' : IDL.Text })],
      [],
    ),
  'refineDecision' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : DecisionResult, 'err' : IDL.Text })],
      [],
    ),
  'runDecision' : IDL.Func(
      [IDL.Text, DecisionRequest],
      [IDL.Variant({ 'ok' : DecisionResult, 'err' : IDL.Text })],
      [],
    ),
  'savePick' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : HistoryEntry, 'err' : IDL.Text })],
      [],
    ),
  'signup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
      [],
    ),
  'undoLastSwipe' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : SwipeRecord, 'err' : IDL.Text })],
      [],
    ),
  'updatePreferences' : IDL.Func(
      [IDL.Text, UserPreferences],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'swipeCount' : IDL.Nat,
    'cuisineType' : IDL.Text,
    'deliveryTime' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'whyThis' : IDL.Text,
    'restaurant' : IDL.Text,
    'reason' : IDL.Text,
  });
  const HistoryEntry = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'feedback' : IDL.Text,
    'savedAt' : IDL.Int,
    'foodItem' : FoodItem,
  });
  const ShareRecord = IDL.Record({
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'shareId' : IDL.Text,
    'foodItem' : FoodItem,
  });
  const UserPreferences = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'dietaryType' : IDL.Text,
    'cuisines' : IDL.Vec(IDL.Text),
    'budget' : IDL.Opt(IDL.Nat),
  });
  const UserPublic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'preferences' : UserPreferences,
  });
  const AuthResponse = IDL.Record({ 'token' : IDL.Text, 'user' : UserPublic });
  const SwipeRecord = IDL.Record({
    'direction' : IDL.Text,
    'userId' : IDL.Text,
    'swipedAt' : IDL.Int,
    'foodId' : IDL.Text,
  });
  const DecisionResult = IDL.Record({
    'sessionId' : IDL.Text,
    'picks' : IDL.Vec(FoodItem),
  });
  const DecisionRequest = IDL.Record({
    'mood' : IDL.Opt(IDL.Text),
    'cuisinePreference' : IDL.Opt(IDL.Text),
    'budgetOverride' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'addHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : HistoryEntry, 'err' : IDL.Text })],
        [],
      ),
    'createShareLink' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ShareRecord, 'err' : IDL.Text })],
        [],
      ),
    'getHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(HistoryEntry), 'err' : IDL.Text })],
        [],
      ),
    'getProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'getSharedPick' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ShareRecord, 'err' : IDL.Text })],
        ['query'],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
        [],
      ),
    'recordSwipe' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SwipeRecord, 'err' : IDL.Text })],
        [],
      ),
    'refineDecision' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : DecisionResult, 'err' : IDL.Text })],
        [],
      ),
    'runDecision' : IDL.Func(
        [IDL.Text, DecisionRequest],
        [IDL.Variant({ 'ok' : DecisionResult, 'err' : IDL.Text })],
        [],
      ),
    'savePick' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : HistoryEntry, 'err' : IDL.Text })],
        [],
      ),
    'signup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
        [],
      ),
    'undoLastSwipe' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : SwipeRecord, 'err' : IDL.Text })],
        [],
      ),
    'updatePreferences' : IDL.Func(
        [IDL.Text, UserPreferences],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };