/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AuthResponse {
    token: string;
    user: UserPublic;
}
export interface UserPreferences {
    notificationsEnabled: boolean;
    dietaryType: string;
    cuisines: Array<string>;
    budget?: bigint;
}
export interface HistoryEntry {
    id: string;
    userId: string;
    feedback: string;
    savedAt: bigint;
    foodItem: FoodItem;
}
export interface UserPublic {
    id: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferences: UserPreferences;
}
export interface DecisionRequest {
    mood?: string;
    cuisinePreference?: string;
    budgetOverride?: bigint;
}
export interface FoodItem {
    id: string;
    name: string;
    tags: Array<string>;
    swipeCount: bigint;
    cuisineType: string;
    deliveryTime: bigint;
    isActive: boolean;
    imageUrl: string;
    rating: number;
    price: bigint;
    whyThis: string;
    restaurant: string;
    reason: string;
}
export interface SwipeRecord {
    direction: string;
    userId: string;
    swipedAt: bigint;
    foodId: string;
}
export interface ShareRecord {
    createdAt: bigint;
    createdBy: string;
    shareId: string;
    foodItem: FoodItem;
}
export interface DecisionResult {
    sessionId: string;
    picks: Array<FoodItem>;
}
export interface backendInterface {
    addHistory(token: string, foodId: string, feedback: string): Promise<{
        __kind__: "ok";
        ok: HistoryEntry;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createShareLink(token: string, foodId: string): Promise<{
        __kind__: "ok";
        ok: ShareRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getHistory(token: string): Promise<{
        __kind__: "ok";
        ok: Array<HistoryEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getProfile(token: string): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getSharedPick(shareId: string): Promise<{
        __kind__: "ok";
        ok: ShareRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    login(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordSwipe(token: string, foodId: string, direction: string): Promise<{
        __kind__: "ok";
        ok: SwipeRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    refineDecision(token: string, sessionId: string, excludeIds: Array<string>): Promise<{
        __kind__: "ok";
        ok: DecisionResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    runDecision(token: string, req: DecisionRequest): Promise<{
        __kind__: "ok";
        ok: DecisionResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    savePick(token: string, foodId: string): Promise<{
        __kind__: "ok";
        ok: HistoryEntry;
    } | {
        __kind__: "err";
        err: string;
    }>;
    signup(name: string, email: string, password: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    undoLastSwipe(token: string): Promise<{
        __kind__: "ok";
        ok: SwipeRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePreferences(token: string, prefs: UserPreferences): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AuthResponse as _AuthResponse, DecisionRequest as _DecisionRequest, DecisionResult as _DecisionResult, HistoryEntry as _HistoryEntry, ShareRecord as _ShareRecord, SwipeRecord as _SwipeRecord, UserPreferences as _UserPreferences, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHistory(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: HistoryEntry;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addHistory(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHistory(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShareLink(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: ShareRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createShareLink(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShareLink(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistory(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<HistoryEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedPick(arg0: string): Promise<{
        __kind__: "ok";
        ok: ShareRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedPick(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedPick(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSwipe(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: SwipeRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSwipe(arg0, arg1, arg2);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSwipe(arg0, arg1, arg2);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async refineDecision(arg0: string, arg1: string, arg2: Array<string>): Promise<{
        __kind__: "ok";
        ok: DecisionResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.refineDecision(arg0, arg1, arg2);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refineDecision(arg0, arg1, arg2);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async runDecision(arg0: string, arg1: DecisionRequest): Promise<{
        __kind__: "ok";
        ok: DecisionResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.runDecision(arg0, to_candid_DecisionRequest_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runDecision(arg0, to_candid_DecisionRequest_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePick(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: HistoryEntry;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.savePick(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePick(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async signup(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async undoLastSwipe(arg0: string): Promise<{
        __kind__: "ok";
        ok: SwipeRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.undoLastSwipe(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.undoLastSwipe(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePreferences(arg0: string, arg1: UserPreferences): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(arg0, to_candid_UserPreferences_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(arg0, to_candid_UserPreferences_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResponse_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResponse): AuthResponse {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    user: _UserPublic;
}): {
    token: string;
    user: UserPublic;
} {
    return {
        token: value.token,
        user: from_candid_UserPublic_n5(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferences: _UserPreferences;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferences: UserPreferences;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        preferences: from_candid_UserPreferences_n7(_uploadFile, _downloadFile, value.preferences)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    dietaryType: string;
    cuisines: Array<string>;
    budget: [] | [bigint];
}): {
    notificationsEnabled: boolean;
    dietaryType: string;
    cuisines: Array<string>;
    budget?: bigint;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        dietaryType: value.dietaryType,
        cuisines: value.cuisines,
        budget: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.budget))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HistoryEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HistoryEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AuthResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AuthResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AuthResponse_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SwipeRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SwipeRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DecisionResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DecisionResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ShareRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ShareRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_HistoryEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<HistoryEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserPublic_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_DecisionRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DecisionRequest): _DecisionRequest {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood?: string;
    cuisinePreference?: string;
    budgetOverride?: bigint;
}): {
    mood: [] | [string];
    cuisinePreference: [] | [string];
    budgetOverride: [] | [bigint];
} {
    return {
        mood: value.mood ? candid_some(value.mood) : candid_none(),
        cuisinePreference: value.cuisinePreference ? candid_some(value.cuisinePreference) : candid_none(),
        budgetOverride: value.budgetOverride ? candid_some(value.budgetOverride) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    dietaryType: string;
    cuisines: Array<string>;
    budget?: bigint;
}): {
    notificationsEnabled: boolean;
    dietaryType: string;
    cuisines: Array<string>;
    budget: [] | [bigint];
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        dietaryType: value.dietaryType,
        cuisines: value.cuisines,
        budget: value.budget ? candid_some(value.budget) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
